version: '3.8'

services:
  # 1. Database Service
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  # 2. Backend Service
  server:
    build: ./server
    container_name: server_container
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/Learning
    depends_on:
      - mongodb
    # Correct place for restart:
    restart: on-failure 

  # 3. Frontend Service
  client:
    build: ./client
    container_name: client_container
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - server
    stdin_open: true 
    tty: true 
    restart: always

volumes:
  mongo-data: